### ISSUE TITLE
Multiple dex files define Lnet/jcip/annotations/GuardedBy

### ISSUE THREAD

**Issue by linxueyi2230** [leanote/leanote-android-old#14]
java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lnet/jcip/annotations/GuardedBy

**Comment by linxueyi2230** [comment]
已经解决，移除apply plugin: 'android-cq'

**Comment by xingstarx** [comment]
这个repo 暂时没维护了，你可以看这个，github.com/leanote/leanote–android  还在迭代中
